default: &default
  adapter: postgresql
  encoding: unicode
  username: unsc_hq
  password: unsc_hq
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: unsc_hq_development

test:
  <<: *default
  database: unsc_hq_test

production:
  <<: *default
  database: unsc_hq_production
